<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['tasks_app_description'] = 'Планировщик задач может быть использован для запуска пакетных заданий в системе, через равные промежутки времени.';
$lang['tasks_app_name'] = 'Планировщик заданий';
$lang['tasks_schedule_configuration_already_exists'] = 'Конфигурация расписания уже существует.';
