<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['tasks_app_description'] = 'The Task Scheduler can be used to run batch jobs on your system at regular time intervals.';
$lang['tasks_app_name'] = 'Task Scheduler';
$lang['tasks_schedule_configuration_already_exists'] = 'Schedule configuration already exists.';
