<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['tasks_app_description'] = 'Harmonogram zadań może być użyty do zlecania zadań masowych w Twoim systemie w regularnych odstępach czasu.';
$lang['tasks_app_name'] = 'Harmonogram zadań';
$lang['tasks_schedule_configuration_already_exists'] = 'Konfiguracja harmonogramu już istnieje.';
